name: Coding Standards

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0']
        swoole: ['4.8.5']

    env:
      TDENGINE_VERSION: ${{ matrix.tdengine }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl
          extensions: >
            :xdebug
            mbstring, json, sockets,
            swoole-swoole/swoole-src@v${{ matrix.swoole }},

      - name: Prepare
        run: composer update

      - name: Test
        run: php ./vendor/bin/php-cs-fixer fix --dry-run --diff
